export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';

export const ADD_WALLET = 'ADD_WALLET';
export const REMOVE_WALLET = 'REMOVE_WALLET';
export const UPDATE_WALLET = 'UPDATE_WALLET';

export const ADD_BUDGET = 'ADD_BUDGET';
export const REMOVE_BUDGET = 'REMOVE_BUDGET';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';

export const ADD_EVENT = 'ADD_EVENT';
export const REMOVE_EVENT = 'REMOVE_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';

export const ADD_SAVINGS = 'ADD_SAVINGS';
export const REMOVE_SAVINGS = 'REMOVE_SAVINGS';
export const UPDATE_SAVINGS = 'UPDATE_SAVINGS';

export const ENABLE_TRAVEL_MODE = 'ENABLE_TRAVEL_MODE';

export const RECALCULATE_CASH_CACHE= 'RECALCULATE_CASH_CACHE';
export const RECALCULATE_TOTAL = 'RECALCULATE_TOTAL';
export const FLUSH_LOCAL_DB = 'FLUSH_LOCAL_DB';

export const RECALCULATE_MONTHS = 'RECALCULATE_MONTHS';
export const RECALCULATE_MONTH = 'RECALCULATE_MONTH';

export const RECALCULATE_WALLET = 'RECALCULATE_WALLET';
export const RECALCULATE_WALLETS = 'RECALCULATE_WALLETS';

export const DEPOSIT_ON_SAVINGS = 'DEPOSIT_ON_SAVINGS';
export const CHANGE_MONTH = 'CHANGE_MONTH';
